export const AVATARS = [
  {
    id: 'gear-bot',
    name: 'Gear-Bot 🤖',
    title: 'Technical Teacher Robot',
    color: '#3B82F6',
    bgColor: '#EFF6FF',
    icon: '🤖',
    svgIcon: 'gear_bot',
    quote: 'Ready to explore every faculty with a technical teacher heart!',
  },
  {
    id: 'tech-fox',
    name: 'Tech Fox 🦊',
    title: 'Coding Fox',
    color: '#F15A24',
    bgColor: '#FFF7ED',
    icon: '🦊',
    svgIcon: 'tech_fox',
    quote: 'Navigating with intelligence and technology!',
  },
  {
    id: 'cadet-cat',
    name: 'Cat Cadet 🐱',
    title: 'Explorer Cat',
    color: '#EC4899',
    bgColor: '#FDF2F8',
    icon: '🐱',
    svgIcon: 'cadet_cat',
    quote: 'Hunting stamps from every faculty!',
  },
  {
    id: 'engineer-bear',
    name: 'Engineer Bear 🐻',
    title: 'Tough Engineering Bear',
    color: '#10B981',
    bgColor: '#ECFDF5',
    icon: '🐻',
    svgIcon: 'engineer_bear',
    quote: 'Ready for any workshop, never give up!',
  },
  {
    id: 'aero-bot',
    name: 'Aero Rocket 🚀',
    title: 'Space Warrior',
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
    icon: '🚀',
    svgIcon: 'aero_bot',
    quote: 'Soaring into the future world of KMUTNB!',
  },
  {
    id: 'design-bunny',
    name: 'Design Bunny 🐰',
    title: 'Designer Bunny',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    icon: '🐰',
    svgIcon: 'design_bunny',
    quote: 'Design life the way you want!',
  },
];
