export const AVATARS = [
  {
    id: 'gear-bot',
    name: 'Gear-Bot 🤖',
    title: 'หุ่นยนต์ครูช่าง',
    color: '#3B82F6',
    bgColor: '#EFF6FF',
    icon: '🤖',
    svgIcon: 'gear_bot',
    quote: 'พร้อมลุยทุกคณะด้วยหัวใจครูช่าง!',
  },
  {
    id: 'tech-fox',
    name: 'Tech Fox 🦊',
    title: 'จิ้งจอกสายโค้ด',
    color: '#F15A24',
    bgColor: '#FFF7ED',
    icon: '🦊',
    svgIcon: 'tech_fox',
    quote: 'นำทางด้วยความฉลาดและเทคโนโลยี!',
  },
  {
    id: 'cadet-cat',
    name: 'Cat Cadet 🐱',
    title: 'เหมียวนักสำรวจ',
    color: '#EC4899',
    bgColor: '#FDF2F8',
    icon: '🐱',
    svgIcon: 'cadet_cat',
    quote: 'ตามล่า Stamp ให้ครบทุกคณะเลย!',
  },
  {
    id: 'engineer-bear',
    name: 'Engineer Bear 🐻',
    title: 'หมีวิศวะสายถึก',
    color: '#10B981',
    bgColor: '#ECFDF5',
    icon: '🐻',
    svgIcon: 'engineer_bear',
    quote: 'ลุยทุก Workshop ไม่มีท้อ!',
  },
  {
    id: 'aero-bot',
    name: 'Aero Rocket 🚀',
    title: 'นักรบอวกาศ',
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
    icon: '🚀',
    svgIcon: 'aero_bot',
    quote: 'ทะยานสู่โลกอนาคต KMUTNB!',
  },
  {
    id: 'design-bunny',
    name: 'Design Bunny 🐰',
    title: 'กระต่ายดีไซน์เนอร์',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    icon: '🐰',
    svgIcon: 'design_bunny',
    quote: 'ออกแบบชีวิตในแบบที่คุณต้องการ!',
  },
];
