export const MISSIONS = [
  {
    id: 'mission-first-step',
    title: 'Mission 01 — First Step 🧭',
    description: 'Join your first activity at KMUTNB Open House',
    requirementType: 'activities',
    targetCount: 1,
    rewardType: 'badge',
    rewardName: 'First Step Badge',
    rewardIcon: '🧭',
    xpReward: 15,
  },
  {
    id: 'mission-activity-hunter',
    title: 'Mission 02 — Activity Hunter 🎯',
    description: 'Collect a total of 5 activities',
    requirementType: 'activities',
    targetCount: 5,
    rewardType: 'reward_access',
    rewardName: 'Limited Open House Sticker Set',
    rewardIcon: '🎁',
    xpReward: 50,
  },
  {
    id: 'mission-faculty-explorer',
    title: 'Mission 03 — Faculty Explorer 🏫',
    description: 'Visit a total of 3 faculties',
    requirementType: 'faculties',
    targetCount: 3,
    rewardType: 'badge',
    rewardName: 'Faculty Explorer Badge',
    rewardIcon: '🏛️',
    xpReward: 30,
  },
  {
    id: 'mission-campus-collector',
    title: 'Mission 04 — Campus Collector 🗺️',
    description: 'Collect 5 Faculty Stamps',
    requirementType: 'faculties',
    targetCount: 5,
    rewardType: 'reward_access',
    rewardName: 'KMUTNB Open House Tote Bag',
    rewardIcon: '🛍️',
    xpReward: 75,
  },
  {
    id: 'mission-kmutnb-master',
    title: 'Mission 05 — KMUTNB Master Explorer 🏆',
    description: 'Visit all 9/9 faculties across the university!',
    requirementType: 'faculties',
    targetCount: 9,
    rewardType: 'special',
    rewardName: 'KMUTNB Special Souvenir + Official Certificate',
    rewardIcon: '👑',
    xpReward: 150,
  },
];

export const REWARDS = [
  {
    id: 'rew-sticker',
    title: 'KMUTNB Sticker Set',
    category: 'Sticker',
    costXP: 50,
    requiredFaculties: 0,
    icon: '🎨',
    description: 'Cute die-cut sticker set of KMUTNB faculties',
    stock: 500,
  },
  {
    id: 'rew-pin',
    title: 'Open House Limited Badge Pin',
    category: 'Pin',
    costXP: 100,
    requiredFaculties: 3,
    icon: '🏅',
    description: 'Premium KMUTNB 2026 metal souvenir badge',
    stock: 250,
  },
  {
    id: 'rew-totebag',
    title: 'KMUTNB Canvas Tote Bag',
    category: 'Bag',
    costXP: 150,
    requiredFaculties: 5,
    icon: '🛍️',
    description: 'High-quality canvas bag printed with Gamified Campus pattern',
    stock: 100,
  },
  {
    id: 'rew-souvenir',
    title: 'KMUTNB Master Souvenir Box',
    category: 'Special Souvenir',
    costXP: 200,
    requiredFaculties: 9,
    icon: '🎁',
    description: 'Special limited gift box for collecting 9/9 faculty stamps',
    stock: 50,
  },
];
