export const MISSIONS = [
  {
    id: 'mission-first-step',
    title: 'Mission 01 — First Step 🧭',
    description: 'เข้าร่วมกิจกรรมแรกใน KMUTNB Open House',
    requirementType: 'activities',
    targetCount: 1,
    rewardType: 'badge',
    rewardName: 'First Step Badge',
    rewardIcon: '🧭',
    xpReward: 15,
  },
  {
    id: 'mission-activity-hunter',
    title: 'Mission 02 — Activity Hunter 🎯',
    description: 'เข้าร่วมกิจกรรมสะสมครบ 5 กิจกรรม',
    requirementType: 'activities',
    targetCount: 5,
    rewardType: 'reward_access',
    rewardName: 'Limited Open House Sticker Set',
    rewardIcon: '🎁',
    xpReward: 50,
  },
  {
    id: 'mission-faculty-explorer',
    title: 'Mission 03 — Faculty Explorer 🏫',
    description: 'ออกเดินทางเยี่ยมชมครบ 3 คณะ',
    requirementType: 'faculties',
    targetCount: 3,
    rewardType: 'badge',
    rewardName: 'Faculty Explorer Badge',
    rewardIcon: '🏛️',
    xpReward: 30,
  },
  {
    id: 'mission-campus-collector',
    title: 'Mission 04 — Campus Collector 🗺️',
    description: 'สะสม Faculty Stamp ครบ 5 คณะ',
    requirementType: 'faculties',
    targetCount: 5,
    rewardType: 'reward_access',
    rewardName: 'KMUTNB Open House Tote Bag',
    rewardIcon: '🛍️',
    xpReward: 75,
  },
  {
    id: 'mission-kmutnb-master',
    title: 'Mission 05 — KMUTNB Master Explorer 🏆',
    description: 'ออกเดินทางพิชิตครบ 9/9 คณะทั่วทั้งมหาวิทยาลัย!',
    requirementType: 'faculties',
    targetCount: 9,
    rewardType: 'special',
    rewardName: 'KMUTNB Special Souvenir + Official Certificate',
    rewardIcon: '👑',
    xpReward: 150,
  },
];

export const REWARDS = [
  {
    id: 'rew-sticker',
    title: 'KMUTNB Sticker Set',
    category: 'Sticker',
    costXP: 50,
    requiredFaculties: 0,
    icon: '🎨',
    description: 'ชุดสติ๊กเกอร์ไดคัทสุดน่ารัก ลายประจำคณะ มจพ.',
    stock: 500,
  },
  {
    id: 'rew-pin',
    title: 'Open House Limited Badge Pin',
    category: 'Pin',
    costXP: 100,
    requiredFaculties: 3,
    icon: '🏅',
    description: 'เข็มกลัดที่ระลึกโลหะ พรีเมียม KMUTNB 2026',
    stock: 250,
  },
  {
    id: 'rew-totebag',
    title: 'KMUTNB Canvas Tote Bag',
    category: 'Bag',
    costXP: 150,
    requiredFaculties: 5,
    icon: '🛍️',
    description: 'กระเป๋าผ้าแคนวาสอย่างดี พิมพ์ลาย Gamified Campus',
    stock: 100,
  },
  {
    id: 'rew-souvenir',
    title: 'KMUTNB Master Souvenir Box',
    category: 'Special Souvenir',
    costXP: 200,
    requiredFaculties: 9,
    icon: '🎁',
    description: 'กล่องของขวัญพิเศษสุดลิมิเต็ด สำหรับผู้สะสมตราประทับครบ 9/9 คณะ',
    stock: 50,
  },
];
